-- Store research intake separately from parking occupancy and core outputs.
create table if not exists public.research_records (
  id bigint generated by default as identity primary key,
  market text not null,
  facility_type text not null,
  research_question text not null,
  created_at timestamptz not null default now()
);

create index if not exists research_records_created_at_idx
  on public.research_records (created_at desc);

alter table public.research_records enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'research_records'
      and policyname = 'Park Now can read research records'
  ) then
    execute 'create policy "Park Now can read research records"
      on public.research_records for select to anon, authenticated using (true)';
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'research_records'
      and policyname = 'Park Now can insert research records'
  ) then
    execute 'create policy "Park Now can insert research records"
      on public.research_records for insert to anon, authenticated with check (true)';
  end if;
end
$$;
