-- Park Now incremental Supabase migration.
-- Existing tables are preserved: public.core_outputs, public.parkin_lots,
-- and public.parking_spaces. This migration does not drop, recreate, seed,
-- rename, or overwrite data in those tables.

-- These supporting tables are not used by the current UI yet, but are part of
-- the documented Park Now data model.
create table if not exists public.occupancy_events (
  id bigint generated by default as identity primary key,
  parking_space_id bigint not null references public.parking_spaces(id) on delete cascade,
  previous_status text check (previous_status in ('available', 'occupied')),
  new_status text not null check (new_status in ('available', 'occupied')),
  recorded_at timestamptz not null default now()
);

create table if not exists public.user_tests (
  id bigint generated by default as identity primary key,
  participant_alias text not null,
  task text not null,
  result text not null,
  feedback text,
  iteration_action text,
  created_at timestamptz not null default now()
);

create table if not exists public.assistant_logs (
  id bigint generated by default as identity primary key,
  question text not null,
  response_type text,
  created_at timestamptz not null default now()
);

-- These indexes use columns already required by the current application.
create index if not exists parking_spaces_lot_space_number_idx
  on public.parking_spaces (parking_lot_id, space_number);

create index if not exists parking_spaces_lot_status_idx
  on public.parking_spaces (parking_lot_id, status);

create index if not exists occupancy_events_space_recorded_at_idx
  on public.occupancy_events (parking_space_id, recorded_at desc);

create index if not exists core_outputs_created_at_idx
  on public.core_outputs (created_at desc);

create index if not exists user_tests_created_at_idx
  on public.user_tests (created_at desc);

create index if not exists assistant_logs_created_at_idx
  on public.assistant_logs (created_at desc);

-- Keep RLS enabled. Existing policies with other names are left untouched.
alter table if exists public.parkin_lots enable row level security;
alter table if exists public.parking_spaces enable row level security;
alter table if exists public.core_outputs enable row level security;
alter table public.occupancy_events enable row level security;
alter table public.user_tests enable row level security;
alter table public.assistant_logs enable row level security;

-- The prototype only needs public read access to parking data.
-- /core loads the three most recent rows and inserts valid recommendations.
-- Supporting prototype data can be recorded without exposing it for public reads.
do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'parkin_lots'
      and policyname = 'Park Now can read parking lots'
  ) then
    execute 'create policy "Park Now can read parking lots"
      on public.parkin_lots for select to anon, authenticated using (true)';
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'parking_spaces'
      and policyname = 'Park Now can read parking spaces'
  ) then
    execute 'create policy "Park Now can read parking spaces"
      on public.parking_spaces for select to anon, authenticated using (true)';
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'core_outputs'
      and policyname = 'Park Now can read core outputs'
  ) then
    execute 'create policy "Park Now can read core outputs"
      on public.core_outputs for select to anon, authenticated using (true)';
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'core_outputs'
      and policyname = 'Park Now can insert core outputs'
  ) then
    execute 'create policy "Park Now can insert core outputs"
      on public.core_outputs for insert to anon, authenticated with check (true)';
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'occupancy_events'
      and policyname = 'Park Now can insert occupancy events'
  ) then
    execute 'create policy "Park Now can insert occupancy events"
      on public.occupancy_events for insert to anon, authenticated with check (true)';
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'user_tests'
      and policyname = 'Park Now can insert user tests'
  ) then
    execute 'create policy "Park Now can insert user tests"
      on public.user_tests for insert to anon, authenticated with check (true)';
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'assistant_logs'
      and policyname = 'Park Now can insert assistant logs'
  ) then
    execute 'create policy "Park Now can insert assistant logs"
      on public.assistant_logs for insert to anon, authenticated with check (true)';
  end if;
end
$$;

-- The current /parking and /dashboard subscriptions listen to parking_spaces.
alter table public.parking_spaces replica identity full;

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'parking_spaces'
  ) then
    alter publication supabase_realtime add table public.parking_spaces;
  end if;
end
$$;
